version: '3.8'

services:
  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 3300:3300
    volumes:
      - db:/yup/lib/mysql

  adminer:
    depends_on:
      - mysqldb
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
      ADMINER_DESIGN: 'pepa-linha-dark'
    ports:
      - 7070:7070

  express:
    depends_on:
      - mysqldb
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    ports:
      - "${PORT}:${PORT}"

volumes:
  db:
